### ISSUE TITLE
Bad scheduling checker

### ISSUE THREAD

**Issue by ArchangelSDY** [Azure/kdebug#80]
# Background
Sometimes pods can be scheduled in a non-HA way. For example, all pods in a deployment scheduled to a single machine, or a single zone. Authoring a deployment with HA is hard for beginners. We should be able to point out such risks and guide users to configure pod spread topology properly.

# Goals
* Detect bad scheduling issues
    * All pods in a deployment scheduled to a single machine.
    * All pods in a deployment scheduled to a single zone, if cluster supports AZ.
* Give general guidance about configuring pod anti-affinity and spread topology

# Non-goals
* No need to detect theoretical issues. Just check current status.

# References
* https://kubernetes.io/docs/concepts/scheduling-eviction/assign-pod-node/#affinity-and-anti-affinity
* https://kubernetes.io/docs/concepts/scheduling-eviction/assign-pod-node/#pod-topology-spread-constraints

**Comment by zackliu** [comment]
A test spec
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                - <node-name>
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80
```
